 Text("welcome").font(.largeTitle)
                .fontWeight(.bold)
                .foregroundColor(.blue)
                .padding()
                .background(Color.yellow)
                .transition(.opacity)
                .cornerRadius(20)
                .shadow(radius: 5)
                .shadow(radius: 4, x: 1, y: 1)
                .shadow(radius: 3, x: 2, y: 2)
